name: build

on:
  push:
    branches:
      - main

jobs:
  BuildRelease:
    runs-on: ubuntu-latest
    name: Checkout Code
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
      - name: Build and Release
        uses: jupiterone/action-npm-build-release@v1
        with:
          npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN_TEST }}
          gh_token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}